### ISSUE TITLE
Convert card #4 to issue

### ISSUE THREAD

**Issue by volodymyr-kushnir** [ruig1992/bsa-git-hw1#1]
Hey, what's up?
You're doing good, everything is okay, I would just like to suggest to convert card #4 in your **Projects** to the issue (they have that function in GitHub, pretty useful) and then closing the issue when the job is done. You could also commit with **"Add comments or whatever (fixes #1)"** (put the proper number of the issue instead of 1, since 1 is this current issue I opened just now) as your commit's message to automatically close the issue.

**Comment by ruig1992** [comment]
Hello, Vladimir! I'm glad to see you here! Thank you, this is a good suggestion. The card was converted to an issue successfully.
