### ISSUE TITLE
Add links on SOLID-headers

### ISSUE THREAD

**Issue by hugo007test** [ruig1992/bsa-git-hw1#5]
Hi! Your article is well designed. But I see that it has a list of all 5 principles, after which each principle is given in more detail with the header at the beginning. Proposal - to make links from the list items to the appropriate headers. This will improve the navigation in the text of the article.

**Comment by ruig1992** [comment]
Hi! Why not? This is indeed a very good enhancement. I will definitely do it right now! :wink:

**Comment by ruig1992** [comment]
Done. Thank you for your advice! :blush:
